{% set version = '0.2.79' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mashr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mashr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mashr/mashr_{{ version }}.tar.gz
  sha256: 158b3670277523fa3168a46a9d80a1f6dd7063091b54584cd170eb70bf85f886

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-abind                      # [build_platform != target_platform]
    - r-ashr                       # [build_platform != target_platform]
    - r-assertthat                 # [build_platform != target_platform]
    - r-mvtnorm                    # [build_platform != target_platform]
    - r-plyr                       # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rcpparmadillo              # [build_platform != target_platform]
    - r-rcppgsl                    # [build_platform != target_platform]
    - r-rmeta                      # [build_platform != target_platform]
    - r-softimpute                 # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - libgomp                      # [not osx]
    - llvm-openmp                  # [osx]
  host:
    - r-base
    - r-abind
    - r-ashr >=2.2_22
    - r-assertthat
    - r-mvtnorm
    - r-plyr
    - r-rcpp >=1.0.8
    - r-rcpparmadillo
    - r-rcppgsl >=0.3.8
    - r-rmeta
    - r-softimpute
    - libgomp                      # [not osx]
    - llvm-openmp                  # [osx]
    - gsl
    - libblas
    - liblapack
  run:
    - r-base
    - r-abind
    - r-ashr >=2.2_22
    - r-assertthat
    - r-mvtnorm
    - r-plyr
    - r-rcpp >=1.0.8
    - r-rcpparmadillo
    - r-rcppgsl >=0.3.8
    - r-rmeta
    - r-softimpute
    - libgomp                      # [win]

test:
  commands:
    - $R -e "library('mashr')"           # [not win]
    - "\"%R%\" -e \"library('mashr')\""  # [win]

about:
  home: https://github.com/stephenslab/mashr
  license: BSD-3-Clause
  summary: Implements the multivariate adaptive shrinkage (mash) method of Urbut et al (2019)
    <DOI:10.1038/s41588-018-0268-8> for estimating and testing large numbers of effects
    in many conditions (or many outcomes). Mash takes an empirical Bayes approach to
    testing and effect estimation; it estimates patterns of similarity among conditions,
    then exploits these patterns to improve accuracy of the effect estimates. The core
    linear algebra is implemented in C++ for fast model fitting and posterior computation.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
